
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
BOOTLOADER = caterina
SPLIT_KEYBOARD = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
SWAP_HANDS_ENABLE = yes

LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
